##
### Developer configuration
##
spring:
  data:
    mongodb:
      port: 27018
      host: localhost
      database: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC



jwt:
  token:
    secretKey: someSecretKey
    expirationSec: 30            # 5 min
    refreshExpirationSec: 900     # 15 min
    header: Authorization
    prefix: Bearer






